---
- name: Check artifacts
  tags:
    - role::artifact
  block:
    - name: Generate undefined value place holder
      ansible.builtin.set_fact:
        __artifact_undefined_place_holder: >-
          {{ "__check_platform_undefined_place_holder__"
             + (99999999999999999999999999999999999999999999999999
                | random
                | to_uuid) }}

    - name: Setup facts with artifacts to manage
      ansible.builtin.set_fact:
        __artifact_to_manage: >-
          {{ (artifact_list
              + ((artifact_load_from_hostvars | bool)
                 | ternary(artifact_hostvars | default([]) | flatten, [])))
             | map("artifact_reverse_combine", artifact_defaults)
             | map("combine", artifact_mandatory, recursive=True) }}

    - name: Setup fact with artifacts with undefined state
      ansible.builtin.set_fact:
        __artifact_state_undefined: >-
          {{ __artifact_to_manage
             | selectattr("state", "undefined")
             | list }}

    - name: Setup facts with artifacts with defined state
      ansible.builtin.set_fact:
        __artifact_state_present: >-
          {{ __artifact_to_manage
             | selectattr("state", "defined")
             | selectattr("state", "equalto", "present")
             | list
             + __artifact_state_undefined }}

        __artifact_state_absent: >-
          {{ __artifact_to_manage
             | selectattr("state", "defined")
             | selectattr("state", "equalto", "absent")
             | list }}

    - name: Setup fact with artifacts present to run once
      ansible.builtin.set_fact:
        __artifact_state_present_run_once: >-
          {{ __artifact_state_present
             | selectattr("run_once", "defined")
             | selectattr("run_once", "equalto", True)
             | list }}

    - name: Setup fact with artifacts present to run n
      ansible.builtin.set_fact:
        __artifact_state_present_run_n: >-
          {{ __artifact_state_present
             | difference(__artifact_state_present_run_once) }}

    - name: Setup facts with artifacts organized by several criteria
      ansible.builtin.set_fact:
        # Absent artifact slist organized by type of run

        __artifact_state_absent_run_once: >-
          {{ __artifact_state_absent
             | selectattr("run_once", "defined")
             | selectattr("run_once", "equalto", True)
             | list }}

        __artifact_state_absent_run_n: >-
          {{ __artifact_state_absent
             | difference(__artifact_state_present_run_once) }}

        # Artifact present list organized by type

        __artifact_type_gitlab_state_present: >-
          {{ __artifact_state_present
             | selectattr("type", "in", ["gitlab", "github"])
             | list }}

        __artifact_type_http_state_present: >-
          {{ __artifact_state_present
             | selectattr('type', "in", ["http", "https"])
             | list }}

        __artifact_type_jenkins_state_present: >-
          {{ __artifact_state_present
             | selectattr("type", "in", ["jenkins"])
             | list }}

        __artifact_type_maven_state_present: >-
          {{ __artifact_state_present
             | selectattr("type", "in", ["maven"])
             | list }}

        # Artifact list organized by unarchive attributes

        __artifact_present_unarchive_run_n: >-
          {{ __artifact_state_present_run_n
             | selectattr("unarchive", "defined")
             | selectattr("unarchive", "equalto", True)
             | list }}

        __artifact_present_unarchive_run_once: >-
          {{ __artifact_state_present_run_once
             | selectattr("unarchive", "defined")
             | selectattr("unarchive", "equalto", True)
             | list }}

        __artifact_present_unarchive_force_root: >-
          {{ __artifact_state_present
             | selectattr("unarchive_force_root", "defined")
             | list }}

        # Artifact list organized by checksum attribute

        __artifact_present_checksum_run_n: >-
          {{ __artifact_state_present_run_n
             | selectattr("checksum", "defined")
             | list }}

        __artifact_present_checksum_run_once: >-
          {{ __artifact_state_present_run_once
             | selectattr("checksum", "defined")
             | list }}

    - name: Setup facts with artifacts type flags
      ansible.builtin.set_fact:
        __artifact_gitlab_gitlab_exist: >-
          {{ __artifact_type_gitlab_state_present | length > 0 }}

        __artifact_maven_exist: >-
          {{ __artifact_type_maven_state_present | length > 0 }}

        __artifact_unarchive_exist: >-
          {{ __artifact_state_present
             | selectattr("unarchive", "defined")
             | selectattr("unarchive", "equalto", True)
             | list | length > 0 }}

    - name: Check artifacts config
      ansible.builtin.assert:
        that:
          - >-
            __artifact_state_present
            | selectattr("id", "undefined")
            | list
            | length == 0
        fail_msg: artifact `id` attribute is required
      tags:
        - role::artifact::check
