{% if item.name is search("^(el6|el7)") %}
# Disable repos mirror list
RUN sed -i -r "s%(^mirrorlist=.*)%#\1%g" /etc/yum.repos.d/*.repo

# Point repos to vault
RUN sed -i -r "s%#baseurl=http://mirror.centos.org/%baseurl=http://vault.centos.org/%g" /etc/yum.repos.d/*.repo
{% endif %}
