{% include "Dockerfile_from.j2" %}
{% include "Dockerfile_env.j2" %}
{% include "Dockerfile_vault.j2" %}
{% include "Dockerfile_python.j2" %}
{% include "Dockerfile_systemv.j2" %}
{% include "Dockerfile_systemd.j2" %}
