{% if item.name is not search("^el6")
      and item.command | default("") == "/sbin/init" %}
RUN if [ $(command -v dnf) ]; then \
      dnf makecache ; \
      dnf --assumeyes install python || true ; \
      dnf --assumeyes install python3 || true ; \
      dnf --assumeyes install sudo python*-dnf bash iproute systemd ; \
      dnf clean all; \
    elif [ $(command -v yum) ]; then \
      yum makecache fast ; \
      yum install -y python || true ; \
      yum install -y python3 || true ; \
      yum install -y sudo yum-plugin-ovl bash iproute systemd ; \
      sed -i "s/plugins=0/plugins=1/g" /etc/yum.conf ; \
      yum clean all; \
    fi

{% if item.name is search("^el7") %}
RUN yum install -y wget
RUN wget https://copr.fedorainfracloud.org/coprs/jsynacek/systemd-backports-for-centos-7/repo/epel-7/jsynacek-systemd-backports-for-centos-7-epel-7.repo -O /etc/yum.repos.d/jsynacek-systemd-centos-7.repo
RUN yum update -y systemd
{% endif %}

{% if item.name is search("^el8") %}
{% endif %}

ENV container docker

RUN rm -f /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup.service ; \
    rm -f /lib/systemd/system/multi-user.target.wants/* ; \
    rm -f /etc/systemd/system/*.wants/* ; \
    rm -f /lib/systemd/system/local-fs.target.wants/* ; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev* ; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl* ; \
    rm -f /lib/systemd/system/basic.target.wants/* ; \
    rm -f /lib/systemd/system/anaconda.target.wants/* ;

VOLUME [ "/sys/fs/cgroup" ]
VOLUME [ "/run" ]
{% endif %}
