---
- name: Converge
  hosts: molecule_hosts
  gather_facts: false
  tasks:
    - name: Setup artifacts
      ansible.builtin.include_role:
        name: amtega.artifact

    - name: Check artifact facts
      ansible.builtin.assert:
        that: artifact_result.tomcat1 is defined

    - name: Check artifact was removed
      ansible.builtin.assert:
        that: artifact_result.tomcat1.changed
      tags:
        - molecule-idempotence-notest
