---
- name: Prepare
  hosts: molecule_hosts
  gather_facts: false
  tasks:
    - name: Setup artifacts to make absent
      ansible.builtin.include_role:
        name: amtega.artifact
      vars:
        artifact_list:
          - id: tomcat1
            type: https
            host: https://archive.apache.org
            path: /dist/tomcat/tomcat-8/v8.5.9/bin
            file: apache-tomcat-8.5.9.tar.gz
            dest_file: tomcat.tar.gz
            checksum_algorithm: sha1
            checksum: >-  # pragma: allowlist secret
              3c800e7affdf93bf4dbcf44bd852904449b786f6
            dest: /tmp
            unarchive: true
            unarchive_creates: /tmp/apache-tomcat-8.5.9
            validate_certs: false
            state: present
            no_log: false

          - id: tomcat2
            type: https
            host: https://archive.apache.org
            path: /dist/tomcat/tomcat-8/v8.5.9/bin
            file: apache-tomcat-8.5.9.tar.gz
            dest_file: tomcat2.tar.gz
            checksum_algorithm: sha1
            checksum: >-  # pragma: allowlist secret
              3c800e7affdf93bf4dbcf44bd852904449b786f6
            dest: /tmp
            validate_certs: false
            state: present
            no_log: false
